# Emulator Management: Create, Start and Wait
before_script:
- chmod +x gradlew

language: android
jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - extra-android-support

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-25

script:
  - "/bin/bash ./gradlew install"
