name: Android build test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build with Gradle
        run: |
          ./gradlew publishToMavenLocal
          ./gradlew lint
